# Generated by Django 6.0 on 2026-03-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='lines',
        ),
        migrations.AddField(
            model_name='line',
            name='stations',
            field=models.ManyToManyField(db_table='subway_station_lines', related_name='lines', to='subway.station'),
        ),
        migrations.AlterField(
            model_name='station',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='line',
            table='subway_line',
        ),
        migrations.AlterModelTable(
            name='station',
            table='subway_station',
        ),
    ]
