# Generated by Django 6.0 on 2025-12-30 04:27

import django.core.validators
import django.db.models.deletion
import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subway', '0002_delete_stationline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('episode_num', models.IntegerField()),
                ('subtitle', models.CharField(max_length=255)),
                ('history_summary', models.TextField()),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, to='subway.station')),
            ],
            options={
                'db_table': 'stories_episode',
            },
        ),
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('cut_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cut_order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('image', models.ImageField(upload_to=stories.models.cut_upload_to)),
                ('caption', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuts', to='stories.episode')),
            ],
            options={
                'db_table': 'cuts',
                'ordering': ['cut_order'],
            },
        ),
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('webtoon_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='webtoons/thumbnails/')),
                ('summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subway.station')),
            ],
            options={
                'db_table': 'webtoons',
            },
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['station', 'episode_num'], name='stories_epi_station_dceea2_idx'),
        ),
        migrations.AddConstraint(
            model_name='cut',
            constraint=models.UniqueConstraint(fields=('episode', 'cut_order'), name='uniq_episode_cut_order'),
        ),
    ]
