# Generated by Django 6.0 on 2026-03-09 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('episode_num', models.IntegerField()),
                ('subtitle', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'episodes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('cut_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
                ('caption', models.TextField(blank=True, null=True)),
                ('cut_order', models.SmallIntegerField()),
                ('episode', models.ForeignKey(db_column='episode_id', on_delete=django.db.models.deletion.CASCADE, related_name='cuts', to='stories.episode')),
            ],
            options={
                'db_table': 'cuts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('webtoon_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='webtoons/thumbnails/')),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, to='subway.station')),
            ],
            options={
                'db_table': 'webtoons',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='webtoon',
            field=models.ForeignKey(db_column='webtoon_id', on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='stories.webtoon'),
        ),
    ]
