# Generated by Django 5.2.8 on 2025-12-18 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='기본 제목', max_length=200)),
                ('image', models.ImageField(upload_to='episodes/')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subway.station')),
            ],
        ),
    ]
