# Generated by Django 6.0 on 2025-12-24 04:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_cut'),
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE stories_cut DROP FOREIGN KEY stories_cut_episode_id_56c9dfb4_fk_stories_episode_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # ✅ 0컬럼 구간 방지: created_at 먼저 추가
        migrations.AddField(
            model_name="episode",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cut",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),

        migrations.CreateModel(
            name="Webtoon",
            fields=[
                ("webtoon_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                ("thumbnail", models.ImageField(blank=True, null=True, upload_to=stories.models.thumbnail_upload_to)),
                ("summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "webtoons"},
        ),

        migrations.AlterModelOptions(name="cut", options={"ordering": ["cut_order"]}),

        # ✅ PK 교체: 기존 id 먼저 제거
        migrations.RemoveField(model_name="cut", name="id"),
        migrations.RemoveField(model_name="episode", name="id"),

        # ✅ 새 PK 추가
        migrations.AddField(model_name="cut", name="cut_id",
            field=models.BigAutoField(primary_key=True, serialize=False)),
        migrations.AddField(model_name="episode", name="episode_id",
            field=models.BigAutoField(primary_key=True, serialize=False)),

        # 나머지 필드 추가
        migrations.AddField(model_name="cut", name="cut_order",
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
        migrations.AddField(model_name="episode", name="episode_num",
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False),
        migrations.AddField(model_name="episode", name="history_summary", field=models.TextField(blank=True, null=True)),
        migrations.AddField(model_name="episode", name="is_published", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="episode", name="published_at", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="episode", name="source_url", field=models.URLField(blank=True, null=True)),
        migrations.AddField(model_name="episode", name="subtitle", field=models.CharField(blank=True, max_length=200, null=True)),

        # ✅ 이제 구필드 제거(0컬럼 안 됨)
        migrations.RemoveField(model_name="cut", name="order"),
        migrations.RemoveField(model_name="episode", name="image"),
        migrations.RemoveField(model_name="episode", name="station"),
        migrations.RemoveField(model_name="episode", name="title"),

        migrations.AlterField(model_name="cut", name="caption", field=models.TextField(blank=True, null=True)),
        migrations.AlterField(model_name="cut", name="image", field=models.ImageField(upload_to=stories.models.cut_upload_to)),

        migrations.AddIndex(model_name="cut", index=models.Index(fields=["episode", "cut_order"], name="cuts_episode_376d22_idx")),
        migrations.AddConstraint(model_name="cut", constraint=models.UniqueConstraint(fields=("episode", "cut_order"), name="uniq_episode_cut_order")),

        migrations.AlterModelTable(name="cut", table="cuts"),
        migrations.AlterModelTable(name="episode", table="episodes"),

        migrations.AddField(model_name="webtoon", name="station",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="subway.station")),
        migrations.AddField(model_name="episode", name="webtoon",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="episodes", to="stories.webtoon")),
        migrations.AddIndex(model_name="episode", index=models.Index(fields=["webtoon", "episode_num"], name="episodes_webtoon_a59102_idx")),
        migrations.AddIndex(model_name="episode", index=models.Index(fields=["is_published", "published_at"], name="episodes_is_publ_667e37_idx")),
        migrations.AddConstraint(model_name="episode", constraint=models.UniqueConstraint(fields=("webtoon", "episode_num"), name="uniq_webtoon_episode_num")),

        # ✅ (선택) 끊어버린 FK 다시 생성 (Django가 자동 복구 안 해줄 수 있어서 안전장치)
        migrations.RunSQL(
            "ALTER TABLE cuts "
            "ADD CONSTRAINT fk_cuts_episode "
            "FOREIGN KEY (episode_id) REFERENCES episodes(episode_id) "
            "ON DELETE CASCADE ON UPDATE CASCADE;",
            reverse_sql="ALTER TABLE cuts DROP FOREIGN KEY fk_cuts_episode;",
        ),
    ]
