# Generated by Django 6.0 on 2025-12-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_webtoon_alter_cut_options_remove_cut_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='caption',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
