# Generated by Django 6.0 on 2025-12-30 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0004_alter_cut_caption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cut",
            name="caption",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cut",
            name="cut_order",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(4),
                ]
            ),
        ),
    ]
